apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbx
  name: bbx
spec:
  containers:
  - command:
      - sh
      - -c
      - "
        \  while : ; do\n
        \        curl ${NGINX_PODIP}:8080/data/1K  2>&1 >  /dev/null ; sleep 60 \n
        \  done"
    image: quay.io/openshifttest/hello-openshift:multiarch
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        privileged: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    name: bbx
    resources: {}
status: {}
